server:
  port: 8080

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/airfood_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      access: unrestricted
    health:
      show-details: always

  metrics:
    tags:
      application: airfood-backend

  prometheus:
    metrics:
      export:
        enabled: true
